radius = 1
max_v = 20
mass = 1
n_H = 100
n_L = 50
height = n_H * radius
width = n_L * radius
atoms_number = 50
max_atoms_number = int(0.25 * min([n_H, n_L]))
k = 5 # min([n_H, n_L])
dt = 1 / (k * max_v)  # krok czasu
frames = 500  # ilość odświeżeń
Dt = frames * dt  # czas eksperymentu
d = radius / 10  # tolerancja zderzenia
radius_plus = radius + d # radius with toleration
